### 
http://localhost:3000/images

###
http://localhost:3000/images/1

###
POST http://localhost:3000/images
Content-Type: application/json

    {
        "image": "image here 2",
        "message": "message here",
        "date": "date here"
    }