### 
http://localhost:3000/images/

###
http://localhost:3000/images/1

###
POST http://localhost:3000/images
Content-Type: application/json
{
    "src": "test image will go here",
    "alt": "test image will go here",
    "caption": "test image will go here",
    "timeStamp": "a time will go here"
}